---
title: "Story 1 - IIJA Funding Distrubtion Relative to Population and Politics"
author: "Alex Ptacek"
date: "2025-09-10"
output: html_document
---

# Packages Used
<details>
<summary>Click to see code for packages used</summary>

```{r message=FALSE}
library(tidyverse)
library(readxl)
library(robotstxt)
library(rvest)
library(janitor)
```

</details>

# Load Data
<details>
<summary>Click to see code for loading data</summary>

```{r}
iija_data <- read_excel("IIJA FUNDING AS OF MARCH 2023.xlsx") |> 
  clean_names()
```

```{r message=FALSE}
paths_allowed("https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population")

pop_data <- read_html("https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population") |> 
  html_element("table") |> 
  html_table() |> 
  clean_names()
```

```{r message=FALSE}
paths_allowed("https://en.wikipedia.org/wiki/2020_United_States_presidential_election")

election_data <- read_html("https://en.wikipedia.org/wiki/2020_United_States_presidential_election") |> 
  html_elements("#mw-content-text > div.mw-content-ltr.ext-chart-js.mw-parser-output > div:nth-child(264) > table") |> 
  html_table()

election_data <- election_data[[1]] |>  
  as_tibble(.name_repair = "minimal") |> 
  select(state = 1, biden = 2, biden2 = 3, trump = 5)
```

</details>

# Data Cleaning
<details>
<summary>Click to see code for cleaning data</summary>

```{r}
pop_data <- pop_data |> 
  mutate(state_or_territory = toupper(state_or_territory),
         state_or_territory = case_when(str_detect(state_or_territory, "VIRGIN IS") ~ "US VIRGIN ISLANDS",
                                        str_detect(state_or_territory, "MARIANA") ~ "NORTHERN MARIANA ISLANDS",
                                        str_detect(state_or_territory, "GUAM") ~ "GUAM",
                                        str_detect(state_or_territory, "SAMOA") ~ "AMERICAN SAMOA",
                                        .default = state_or_territory))

election_data <- election_data |> 
  mutate(state = toupper(state),
         state = str_replace_all(state, "[^A-Za-z0-9 ]", ""),
         state = ifelse(str_detect(state, "(?i)maine") | str_detect(state, "(?i)nebraska"),
                        str_remove_all(state, " "), state),
         state = ifelse(str_detect(state, "NEVADA"), "NEVADA", state),
         state = ifelse(str_detect(state, "NEW JERSEY"), "NEW JERSEY", state),
         state = ifelse(str_detect(state, "TEXAS"), "TEXAS", state))

data <- iija_data |> 
  mutate(state_teritory_or_tribal_nation = ifelse(state_teritory_or_tribal_nation == "DELEWARE", "DELAWARE",
                                                  state_teritory_or_tribal_nation)) |> 
  left_join(pop_data |> select(1,3),
            by = join_by(state_teritory_or_tribal_nation == state_or_territory)) |> 
  left_join(election_data,
            by = join_by(state_teritory_or_tribal_nation == state))


# Tribal Communities population data comes from the U.S. Census:
# https://www.census.gov/library/stories/2023/10/2020-census-dhc-a-aian-population.html
data <- data |> 
  mutate(census_population_8_9_a_2 = str_remove_all(census_population_8_9_a_2, ","),
         census_population_8_9_a_2 = as.numeric(census_population_8_9_a_2),
         census_population_8_9_a_2 = ifelse(state_teritory_or_tribal_nation == "TRIBAL COMMUNITIES",
                                            6605593, census_population_8_9_a_2),
         biden = str_remove_all(biden, ","),
         biden = as.numeric(biden),
         biden2 = str_remove_all(biden2, "[%]"),
         biden2 = as.numeric(biden2),
         trump = str_remove_all(trump, ","),
         trump = as.numeric(trump))
```

</details>

# Visualization 1

```{r fig.height=8, fig.width=10}
viz1_data <- data |> 
  mutate(fund_perc = total_billions/sum(total_billions),
         pop_perc = census_population_8_9_a_2/ sum(census_population_8_9_a_2),
         perc_diff = fund_perc/pop_perc)

viz1_data |> 
  ggplot(aes(x = perc_diff,
             y = reorder(state_teritory_or_tribal_nation, abs(perc_diff)))) +
  geom_col(fill = ifelse(abs(viz1_data$perc_diff) > 2, "orange", "grey")) +
  theme_minimal() +
  scale_x_continuous(n.breaks = 10,
                     labels = scales::percent) +
  geom_vline(xintercept = 2, lty = 2, color = "orange4", linewidth = 1) +
  labs(title = "IIJA Funding for U.S States and Territories Relative to thier Total Population Percentage",
       subtitle = "Almost a quarter of states and territories received IIJA funding greater than 2x than their population percentage.",
       y = "",
       x = "")
```


```{r fig.height=8, fig.width=10}
viz2_data <- data |> 
  drop_na(biden) |> 
  mutate(fund_perc = total_billions/sum(total_billions),
         pop_perc = biden/ sum(biden),
         perc_diff = biden2/fund_perc,
         fill_col = ifelse(biden > trump, "blue", "red"))

viz2_data |> 
  ggplot(aes(x = perc_diff,
             y = reorder(state_teritory_or_tribal_nation, abs(perc_diff)))) +
  geom_col(fill = viz2_data$fill_col) +
  theme_minimal() +
  scale_x_continuous(n.breaks = 11,
                     labels = scales::percent) +
  labs(title = "IIJA Funding for U.S States and Territories Relative to thier Total Population Percentage",
       subtitle = "Almost a quarter of states and territories received IIJA funding greater than 2x than their population percentage.",
       y = "",
       x = "Actual vs. Expected Funding")
```


```{r}
viz2_data |> 
  ggplot(aes(x = biden2, y = fund_perc)) +
  geom_point(color = viz2_data$fill_col) +
  geom_text(label = viz2_data$state_teritory_or_tribal_nation, size = 2) +
  theme_minimal()
```









































